update publish stuff

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -98,6 +98,14 @@ stages:
             echo $CI_KITWARE_SECRET
             echo $TWINE_USERNAME
 
+            # ADD RELEVANT VARIABLES TO GITLAB SECRET VARIABLES
+            # https://gitlab.kitware.com/computer-vision/netharn/-/settings/ci_cd
+            # Note that it is important to make sure that these variables are
+            # only decrpyted on protected branches by selecting the protected
+            # and masked option. Also make sure you have master and release
+            # branches protected.
+            # https://gitlab.kitware.com/computer-vision/netharn/-/settings/repository#js-protected-branches-settings
+
             # HOW TO ENCRYPT YOUR SECRET GPG KEY
             IDENTIFIER="travis-ci-Erotemic"
             GPG_KEYID=$(gpg --list-keys --keyid-format LONG "$IDENTIFIER" | head -n 2 | tail -n 1 | awk '{print $1}' | tail -c 9)
@@ -113,10 +121,13 @@ stages:
             GLKWS=$CI_KITWARE_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -e -a -in dev/ci_public_gpg_key.pgp > dev/ci_public_gpg_key.pgp.enc
             GLKWS=$CI_KITWARE_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -e -a -in dev/ci_secret_gpg_key.pgp > dev/ci_secret_gpg_key.pgp.enc
             GLKWS=$CI_KITWARE_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -e -a -in dev/gpg_owner_trust > dev/gpg_owner_trust.enc
-            echo $KEYID > dev/public_gpg_key
+            echo $GPG_KEYID > dev/public_gpg_key
 
             # Test decrpyt
-            GLKWS=$CI_KITWARE_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/ci_public_gpg_key.pgp.enc
+            cat dev/public_gpg_key
+            GLKWS=$CI_KITWARE_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/ci_public_gpg_key.pgp.enc 
+            GLKWS=$CI_KITWARE_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/gpg_owner_trust.enc 
+            GLKWS=$CI_KITWARE_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/ci_secret_gpg_key.pgp.enc 
 
             source $(secret_unloader.sh)
 
@@ -138,30 +149,25 @@ stages:
     script: 
         - export GPG_EXECUTABLE=gpg
         - export GPG_KEYID=$(cat dev/public_gpg_key)
+        - echo "GPG_KEYID = $GPG_KEYID"
         - $GPG_EXECUTABLE --version
         - openssl version
+        - $GPG_EXECUTABLE --list-keys
         - $GPG_EXECUTABLE --list-keys
         # Decrypt and import GPG Keys / trust
         # note CI_KITWARE_SECRET is a protected variables only available on master and release branch
         - GLKWS=$CI_KITWARE_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/ci_public_gpg_key.pgp.enc | $GPG_EXECUTABLE --import 
         - GLKWS=$CI_KITWARE_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/gpg_owner_trust.enc | $GPG_EXECUTABLE --import-ownertrust
         - GLKWS=$CI_KITWARE_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/ci_secret_gpg_key.pgp.enc | $GPG_EXECUTABLE --import 
+        - $GPG_EXECUTABLE --list-keys  || echo "first one fails for some reason"
+        - $GPG_EXECUTABLE --list-keys  
         # The publish script only builds wheels and does gpg signing if TAG_AND_UPLOAD is False
-        - MB_PYTHON_TAG=$MB_PYTHON_TAG \
-            USE_GPG=True \
-            GPG_KEYID=$KEYID \
-            TWINE_PASSWORD=$TWINE_PASSWORD \
-            TWINE_USERNAME=$TWINE_USERNAME \
-            GPG_EXECUTABLE=$GPG_EXECUTABLE \
-            DEPLOY_BRANCH=release \
-            TAG_AND_UPLOAD=False \
-            ./publish.sh
+        - MB_PYTHON_TAG=$MB_PYTHON_TAG USE_GPG=True GPG_KEYID=$GPG_KEYID TWINE_PASSWORD=$TWINE_PASSWORD TWINE_USERNAME=$TWINE_USERNAME GPG_EXECUTABLE=$GPG_EXECUTABLE DEPLOY_BRANCH=release TAG_AND_UPLOAD=False ./publish.sh 
 
     artifacts:
         paths:
-            - wheelhouse/*.asc
-            - wheelhouse/*.whl
             - dist/*.asc
+            - dist/*.tar.gz
             - dist/*.whl
 
     only:
@@ -183,20 +189,23 @@ stages:
     script: 
         - export GPG_EXECUTABLE=gpg
         - export GPG_KEYID=$(cat dev/public_gpg_key)
+        - echo "GPG_KEYID = $GPG_KEYID"
         - $GPG_EXECUTABLE --version
         - openssl version
         - $GPG_EXECUTABLE --list-keys
-        # GPG info should already have been imported
-        - MB_PYTHON_TAG=$MB_PYTHON_TAG \
-            USE_GPG=True \
-            GPG_KEYID=$KEYID \
-            CURRENT_BRANCH=release \
-            TWINE_PASSWORD=$TWINE_PASSWORD \
-            TWINE_USERNAME=$TWINE_USERNAME \
-            GPG_EXECUTABLE=$GPG_EXECUTABLE \
-            DEPLOY_BRANCH=release \
-            TAG_AND_UPLOAD=False \
-            ./publish.sh
+        - $GPG_EXECUTABLE --list-keys
+        # Decrypt and import GPG Keys / trust
+        # note CI_KITWARE_SECRET is a protected variables only available on master and release branch
+        - GLKWS=$CI_KITWARE_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/ci_public_gpg_key.pgp.enc | $GPG_EXECUTABLE --import 
+        - GLKWS=$CI_KITWARE_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/gpg_owner_trust.enc | $GPG_EXECUTABLE --import-ownertrust
+        - GLKWS=$CI_KITWARE_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/ci_secret_gpg_key.pgp.enc | $GPG_EXECUTABLE --import 
+        - $GPG_EXECUTABLE --list-keys  || echo "first one fails for some reason"
+        - $GPG_EXECUTABLE --list-keys  
+        # Install twine
+        - pip install six pyopenssl ndg-httpsclient pyasn1 -U 
+        - pip install requests[security] twine 
+        # Execute the publish script for real this time
+        - MB_PYTHON_TAG=$MB_PYTHON_TAG USE_GPG=True GPG_KEYID=$GPG_KEYID TWINE_PASSWORD=$TWINE_PASSWORD TWINE_USERNAME=$TWINE_USERNAME GPG_EXECUTABLE=$GPG_EXECUTABLE CURRENT_BRANCH=release DEPLOY_BRANCH=release TAG_AND_UPLOAD=yes ./publish.sh 
             
     only:
         refs:
@@ -225,6 +234,8 @@ test_full/cp37-cp37m-linux:
     image:
         python:3.7
 
+
+# for universal builds we only need to gpg sign once
 gpgsign/cp37-cp37m-linux:
     <<: 
         - *gpgsign_template
@@ -253,17 +264,17 @@ test_full/cp36-cp36m-linux:
     image:
         python:3.6
 
-gpgsign/cp36-cp36m-linux:
-    <<: 
-        - *gpgsign_template
-    image:
-        python:3.6
+#gpgsign/cp36-cp36m-linux:
+#    <<: 
+#        - *gpgsign_template
+#    image:
+#        python:3.6
 
-deploy/cp36-cp36m-linux:
-    <<: 
-        - *deploy_template
-    image:
-        python:3.6
+#deploy/cp36-cp36m-linux:
+#    <<: 
+#        - *deploy_template
+#    image:
+#        python:3.6
 
 
 # ---------------
@@ -281,17 +292,17 @@ test_full/cp35-cp35m-linux:
     image:
         python:3.5
 
-gpgsign/cp35-cp35m-linux:
-    <<: 
-        - *gpgsign_template
-    image:
-        python:3.5
+#gpgsign/cp35-cp35m-linux:
+#    <<: 
+#        - *gpgsign_template
+#    image:
+#        python:3.5
 
-deploy/cp35-cp35m-linux:
-    <<: 
-        - *deploy_template
-    image:
-        python:3.5
+#deploy/cp35-cp35m-linux:
+#    <<: 
+#        - *deploy_template
+#    image:
+#        python:3.5
 
 
 # ---------------
@@ -309,14 +320,14 @@ test_full/cp27-cp27mu-linux:
     image:
         python:2.7
 
-gpgsign/cp27-cp27mu-linux:
-    <<: 
-        - *gpgsign_template
-    image:
-        python:2.7
+#gpgsign/cp27-cp27mu-linux:
+#    <<: 
+#        - *gpgsign_template
+#    image:
+#        python:2.7
 
-deploy/cp27-cp27mu-linux:
-    <<: 
-        - *deploy_template
-    image:
-        python:2.7
+#deploy/cp27-cp27mu-linux:
+#    <<: 
+#        - *deploy_template
+#    image:
+#        python:2.7
